---
- name: Setup Splunk Standalone Server
  hosts: splunk
  become: yes
  vars_files:
    - group_vars/all.yml

  vars:
    tutorial_data_url: "https://docs.splunk.com/images/Tutorial/tutorialdata.zip"
    botsv3_dataset_url: "https://botsdataset.s3.amazonaws.com/botsv3/botsv3_data_set.tgz"

    sample_data_apps:
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/eventgen_721.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/ta-apache_access_eventgen_103.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/ta-fwlog_eventgen_103.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/ta-squid_proxy_eventgen_103.tgz"

    additional_apps:
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/cisco-endpoint-security-analytics-cesa_407.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/code42-for-splunk-legacy_3012.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/decrypt_231.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/microsoft-365-app-for-splunk_331.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/osquery-app-for-splunk_060.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/sa-cim_vladiator_200.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-add-on-for-amazon-web-services-aws_791.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-add-on-for-cisco-asa_520.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-add-on-for-microsoft-azure_420.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-add-on-for-microsoft-cloud-services_543.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-add-on-for-microsoft-office-365_480.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-add-on-for-microsoft-sysmon_1062.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-add-on-for-microsoft-windows_901.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-add-on-for-symantec-endpoint-protection_341.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-add-on-for-unix-and-linux_1000.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-app-for-stream_813.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-common-information-model-cim_602.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-es-content-update_511.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/splunk-security-essentials_381.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/ta-for-code42-app-for-splunk_3012.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/url-toolbox_194.tgz"
      - "https://raw.githubusercontent.com/SoftManiaTech/Bots_V3_Splunkbase_apps/main/virustotal-workflow-actions-for-splunk_020.tgz"

  tasks:
    - name: Pause to ensure file download completion
      pause:
        seconds: 160

    - name: Ensure Splunk User Exists
      user:
        name: splunk
        shell: /bin/bash
        createhome: yes

    - name: Download Tutorial Data
      get_url:
        url: "{{ tutorial_data_url }}"
        dest: /tmp/tutorialdata.zip
        mode: '0644'
      register: tutorial_data
      retries: 3
      delay: 10
      until: tutorial_data is succeeded

    - name: Add Tutorial Data to Splunk Monitoring
      become_user: splunk
      shell: "/opt/splunk/bin/splunk add monitor /tmp/tutorialdata.zip -host_segment 3 -disabled 0 -auth admin:{{ splunk_instance.splunk_admin_password }}"
      args:
        executable: /bin/bash

    - name: Download Sample Data Apps
      become_user: splunk
      get_url:
        url: "{{ item }}"
        dest: "/tmp/{{ item | basename }}"
        mode: '0644'
      loop: "{{ sample_data_apps }}"
      loop_control:
        loop_var: app_url
      register: sample_app
      retries: 3
      delay: 10
      until: sample_app is succeeded

    - name: Install Sample Data Apps
      become_user: splunk
      shell: "/opt/splunk/bin/splunk install app '/tmp/{{ item | basename }}' -auth admin:{{ splunk_instance.splunk_admin_password }}"
      args:
        executable: /bin/bash
      loop: "{{ sample_data_apps }}"
      loop_control:
        loop_var: app_url
      notify: Restart Splunk

    - name: Download BOTS v3 Dataset
      get_url:
        url: "{{ botsv3_dataset_url }}"
        dest: "/tmp/botsv3_data_set.tgz"
        mode: '0644'
      register: botsv3
      retries: 3
      delay: 10
      until: botsv3 is succeeded

    - name: Install BOTS v3 Dataset
      become_user: splunk
      shell: "/opt/splunk/bin/splunk install app '/tmp/botsv3_data_set.tgz' -auth admin:{{ splunk_instance.splunk_admin_password }}"
      args:
        executable: /bin/bash
      notify: Restart Splunk

    - name: Download Additional Splunk Apps
      become_user: splunk
      get_url:
        url: "{{ item }}"
        dest: "/tmp/{{ item | basename }}"
        mode: '0644'
      loop: "{{ additional_apps }}"
      loop_control:
        loop_var: app_url
      register: additional_app
      retries: 3
      delay: 10
      until: additional_app is succeeded

    - name: Install Additional Splunk Apps
      become_user: splunk
      shell: "/opt/splunk/bin/splunk install app '/tmp/{{ item | basename }}' -auth admin:{{ splunk_instance.splunk_admin_password }}"
      args:
        executable: /bin/bash
      loop: "{{ additional_apps }}"
      loop_control:
        loop_var: app_url
      notify: Restart Splunk

    - name: Ensure Splunk is Running
      become_user: splunk
      shell: "/opt/splunk/bin/splunk status || /opt/splunk/bin/splunk start"
      args:
        executable: /bin/bash

  handlers:
    - name: Restart Splunk
      become_user: splunk
      shell: "/opt/splunk/bin/splunk restart"
      args:
        executable: /bin/bash