version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform and Ansible..."
      - yum install -y unzip wget ansible
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
      - ansible --version
      
  post_build:
    commands:
      - echo "Deployment Completed Successfully!"