version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform and Ansible..."
      - yum install -y unzip wget ansible
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
      - ansible --version

  build:
    commands:
      - echo "Build Mode: ${build_mode}"
      - |
        if [ "${build_mode}" == "ec2_only" ]; then
          echo "==== Running EC2 Only Deployment ===="
          cd ec2_only
          chmod +x scripts/check_key.sh
          terraform init
          terraform apply -auto-approve
          exit 0
        fi

        if [ "${build_mode}" == "splunk_install" ]; then
          echo "==== Running EC2 Splunk Deployment ===="
          cd ec2_splunk
          chmod +x scripts/check_key.sh
          terraform init
          terraform apply -auto-approve
          exit 0
        fi

        if [ "${build_mode}" == "splunk_ansible" ]; then
          echo "==== Running EC2 Splunk + Ansible Deployment ===="
          cd ec2_splunk_ansible
          chmod +x scripts/check_key.sh
          terraform init
          terraform apply -auto-approve
          echo "Waiting for EC2 SSH to be ready..."
          sleep 60
          echo "Running Ansible Playbook..."
          ansible-playbook -i inventory.ini botsv3-setup.yml
          exit 0
        fi

        echo "Invalid build_mode specified!"
        exit 1

artifacts:
  files:
    - '**/*'
